### ISSUE TITLE
workflows adjustments?

### ISSUE THREAD

**Issue by pdgilbert** [michaelbeaumont/dht-sensor#7]
If I had understood `workflows` I would have activated it on my own fork before making a pull request. I think my pull request is now going to cause a `workflows` run on `michaelbeaumont:main` every time I push to my fork. So here is the status and what I think may be a problem:

-I have fixed the `rustfmt` and some of the `clippy` problems. The remaining problem is that `clippy` cannot be run with `--all-features` because only one MCU can be specified. I think the solution to this is to modify the `ci.yaml` file by adding a strategy.matrix and adjust the clippy arg:
```
strategy:
  matrix:
    mcu: [stm32f042, stm32f103, stm32f401, stm32f411]  #plus others if this works
    dht: [dht11, dht22]
...
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features ${{ matrix.mcu }},${{ matrix.dht }} -- -D warnings
```

- The `package` job needs an mcu specified as a feature:
```
cargo package   --features stm32f042
```
otherwise there is an error `no 'InputPin' in 'digital::v2'` . I think this is because the trait does not get resolved without a package that the feature pulls in (but I'm just guessing).

- The `build_and_test` job step `Build` also cannot be run with `--all-features` because only one MCU can be specified.
```
cargo build --release  --features stm32f042
```

I have now activated workflows on my fork and will momentarily push the changes to my code and the `ci.yaml` file. If that activates a workflow job on `michaelbeaumont:main` then that job may not allow me to specify a new ci.yaml file. (It could be considered a security risk, or it could be well sandboxed.)

The `strategy.matrix` could also be applied in the  `package` and `build_and_test` jobs, but I will start slowly. (I'm doing this with just a couple of hours crash study of workflows). Please let me know if you know a better solution.
